### ISSUE TITLE
suds.TypeNotFound: Type not found: 'IsPlatformObject'

### ISSUE THREAD

**Issue by johnjiang** [salesforce-marketingcloud/FuelSDK-Python#29]
Running the following code:

```
import ET_Client
myclient = ET_Client.ET_Client()
triggeredsend = ET_Client.ET_TriggeredSend()
triggeredsend.auth_stub = myclient
results = triggeredsend.get()
print results
```

Gives me:

```
No handlers could be found for logger "suds.umx.typed"
Traceback (most recent call last):
  File "/my/path/et.py", line 113, in <module>
    results = triggeredsend.get()
  File "/my/path/lib/python2.7/site-packages/FuelSDK/rest.py", line 288, in get
    obj = ET_Get(self.auth_stub, self.obj_type, props, search_filter)
  File "/my/path/lib/python2.7/site-packages/FuelSDK/rest.py", line 192, in __init__
    response = auth_stub.soap_client.service.Retrieve(ws_retrieveRequest)       
  File "/my/path/lib/python2.7/site-packages/suds/client.py", line 538, in __call__
    return client.invoke(args, kwargs)
  File "/my/path/lib/python2.7/site-packages/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/my/path/lib/python2.7/site-packages/suds/client.py", line 643, in send
    result = self.succeeded(binding, reply.message)
  File "/my/path/lib/python2.7/site-packages/suds/client.py", line 678, in succeeded
    reply, result = binding.get_reply(self.method, reply)
  File "/my/path/lib/python2.7/site-packages/suds/bindings/binding.py", line 156, in get_reply
    result = self.replycomposite(rtypes, nodes)
  File "/my/path/lib/python2.7/site-packages/suds/bindings/binding.py", line 230, in replycomposite
    sobject = unmarshaller.process(node, resolved)
  File "/my/path/lib/python2.7/site-packages/suds/umx/typed.py", line 66, in process
    return Core.process(self, content)
  File "/my/path/lib/python2.7/site-packages/suds/umx/core.py", line 48, in process
    return self.append(content)
  File "/my/path/lib/python2.7/site-packages/suds/umx/core.py", line 63, in append
    self.append_children(content)
  File "/my/path/lib/python2.7/site-packages/suds/umx/core.py", line 140, in append_children
    cval = self.append(cont)
  File "/my/path/lib/python2.7/site-packages/suds/umx/core.py", line 61, in append
    self.start(content)
  File "/my/path/lib/python2.7/site-packages/suds/umx/typed.py", line 80, in start
    raise TypeNotFound(content.node.qname())
suds.TypeNotFound: Type not found: 'IsPlatformObject'
```

**Comment by jdnrg** [comment]
I am also encountering this error
